db2-hr:
  type: db2
  host: localhost
  port: 50000
  database: hr
  user: my_user
  password: my_pass
psql-hr:
  type: postgresql
  host: localhost
  port: 5433
  database: postgres
  user: postgres
  password: postgres
mysql-hr:
  type: mysql
  host: localhost
  port: 13306
  database: hr
  user: my_user
  password: my_pass
  debug: True
sqlserver-hr:
  type: sqlserver
  host: localhost
  port: 11433
  database: tempdb
  user: sa
  password: 1Secure*Password1
oracle-hr:
  type: oracle
  host: localhost
  port: 11521
  database: xe
  user: system
  password: oracle
  oracle_thick_mode: true
#  oracle_thick_mode_lib_dir: /path/to/oracle/driver
cache:
  type: redis
  host: localhost
  port: 12554
cassandra:
  type: cassandra
  hosts: ["localhost"]
  port: 9042
