{
 "title": "Datayoga",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Incoming records rate(by 10 mins)",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(incoming_records_total[10m]))",
     "legendFormat": "Incoming records"
    }
   ]
  },
  {
   "title": "Processed records rate(by 10 min)",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum(rate(processed_records_total[10m]))",
     "legendFormat": "Processed"
    },
    {
     "expr": "sum(rate(filtered_records_total[10m]))",
     "legendFormat": "Filtered"
    },
    {
     "expr": "sum(rate(rejected_records_total[10m]))",
     "legendFormat": "Rejected"
    }
   ]
  },
  {
   "title": "Processed records(abs)",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "targets": [
    { "expr": "sum(processed_records_total)", "legendFormat": "Processed" },
    { "expr": "sum(filtered_records_total)", "legendFormat": "Filtered" },
    { "expr": "sum(rejected_records_total)", "legendFormat": "Rejected" }
   ]
  }
 ]
}