version: "3.9"

services:
  postgres:
    image: postgres
    container_name: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Password123
      - POSTGRES_DB=mydb
    ports:
      - "5432:5432"
    restart: unless-stopped
    networks:
      - service

networks:
  service:
    external: true
