version: "3.9"

services:

  mysql:
    image: mysql
    container_name: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=Password123
      - MYSQL_DATABASE=mydb
    ports:
      - "3306:3306"
    restart: unless-stopped
    networks:
      - service

networks:
  service:
    external: true
