version: "3.9"

services:

  dy-dev:
    platform: linux/amd64
    build:
      context: ../
      dockerfile: ./dev/Dockerfile
    container_name: dy-dev
    volumes:
      - ../cli:/opt/cli
      - ../core:/opt/core
      - ./work:/opt/work
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
    networks:
      - service

networks:
  service:
    external: true