#!/usr/local/bin/python

import os
import sys

from datayoga.__main__ import main

if os.environ.get("REMOTE_DEBUG", "").lower() in ("pycharm", "idea"):
    try:
        import pydevd_pycharm
    except ImportError:
        print("pydevd_pycharm not found. Please install it.")
        sys.exit(-1)

    port = int(os.environ.get("REMOTE_DEBUG_PORT", 12345))
    host = os.environ.get("REMOTE_DEBUG_HOST", "host.docker.internal")

    pydevd_pycharm.settrace(host, port=port, stdoutToServer=True, stderrToServer=True)


if __name__ == "__main__":
    if os.environ.get("PROFILE", "").lower() in ("true", "1"):
        import cProfile as profile
        from time import time
        pr = profile.Profile()
        pr.enable()
        try:
            main()
        finally:
            pr.dump_stats(f"{int(time())}.pstat")
            pr.print_stats(sort="cumtime")
    else:
        sys.exit(main())
