input:
  uses: files.read_csv
  with:
    file: /home/oren/Downloads/airbnb_open_data.csv
    batch_size: 2500
steps:
  - uses: redis.write
    with:
      connection: cache
      command: HSET
      key:
        expression: id
        language: jmespath
