#
# read CSV from airbnb
#
- uses: read_csv
  with:
    file: airbnb_open_data.csv
    batch_size: 250
#
# add a calculated field using SQL expression
#
- uses: add_field
  with:
    field: total_price
    expression: price + `service fee`
    language: sql
#
# customize the key we will use in Redis
#
- uses: sentiment
  with:
    field: NAME
    target_field: sentiment
- uses: add_field
  with:
    field: id
    expression: join(':',['airbnb',"country code",'id',id])
    language: jmespath
- uses: write_redis
  with:
    connection: cache
    command: HSET
    key_field: id
