# Jekyll configuration file (used by GitHub Pages)
remote_theme: just-the-docs/just-the-docs
source: docs
title: DataYoga
name: DataYoga
description: DataYoga is a framework for building and running streaming or batch data pipelines.

markdown: kramdown
search_enabled: false

back_to_top: true
back_to_top_text: "Back to top"

footer_content: "Copyright DataYoga"

# Aux links for the upper right navigation
aux_links:
  "DataYoga on GitHub":
    - "//github.com/datayoga-io"
