name: Generate JSON Schema

on:
  workflow_dispatch:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.8"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install setuptools wheel poetry
      - name: Install prettier
        run: npm install --global prettier
      - name: Build datayoga-core
        run: |
          cd core
          poetry build
      - name: Generate DataYoga Job Schema
        run: |
          python -c "import json; from datayoga_core.job import Job; schema = Job.get_json_schema(); open('schemas/job.schema.json', 'w').write(json.dumps(schema))"
      - name: Prettify JSON Schema files
        run: prettier --write "schemas/**/*.json"
      - name: Push to repo
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git diff --cached --exit-code || git commit -m "update json schemas"
          git push --force
