name: generate docs for jsonschema
on:
  workflow_dispatch:
  pull_request:

jobs:
  docs:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.ref }}

      # Setup node for jsonschema to markdown
      - uses: actions/setup-node@v3
        with:
          node-version: 14

      - name: Generate resource schema doc
        run: |
          rm -rf ./docs/reference
          mkdir ./docs/reference
          for schema in ./datayoga-py/datayoga/resources/schemas/*.schema.json; \
            do echo ${schema}; npx jsonschema2mk --schema ${schema} --extension yaml-examples \
              --extension front-matter --fm.parent "Reference" > \
            ./docs/reference/${schema}.md; done;

      # generate the markdown from json schema
      - name: Generate block schema doc
        run: |
          rm -rf ./docs/reference/blocks
          mkdir ./docs/reference/blocks
          for schema in ./datayoga-py/datayoga/blocks/**/*.schema.json; \
            do echo ${schema}; npx jsonschema2mk --schema ${schema} --extension yaml-examples \
              --extension front-matter --fm.parent "Blocks" --fm.grand_parent "Reference" > \
            ./docs/reference/blocks/$(awk -F/ '{ print $(NF-1) }' <<<"${schema}").md; done;

      - name: Push to repo
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git diff --cached --exit-code || git commit -m "update autogenerated docs"
          git push
