name: generate docs for jsonschema
on:
  workflow_dispatch:
  pull_request:

jobs:
  docs:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.ref }}

      # Setup node for jsonschema to markdown
      - uses: actions/setup-node@v3
        with:
          node-version: 14
      # generate the markdown from json schema
      - name: generate block schema doc
        run: |
          rm -rf ./docs/blocks
          mkdir ./docs/blocks
          for schema in ./src/datayoga/blocks/**/*.schema.json; \
            do npx jsonschema2mk@latest --schema $schema --extension yaml-examples \
              --extension front-matter --fm.parent "Blocks Reference" --fm.layout page > \
            ./docs/blocks/$(awk -F/ '{ print $(NF-1) }' <<<"$schema").md; done;
          sed -i '/<a name="root"><\/a>/d' ./docs/blocks/*.md
      - name: push to repo
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git diff --cached --exit-code || git commit -m "update autogenerated docs"
          git push
