name: integration-tests
on:
  workflow_dispatch:
  pull_request:
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true
jobs:
  integration-tests:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      # Setup Python (faster than using Python container)
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.8"

      - name: Build and Install CLI
        run: |
          cd cli
          pip install poetry
          poetry build
          pip install dist/*.whl

      - name: Install dependencies
        run: |
          curl https://download.oracle.com/otn_software/linux/instantclient/218000/instantclient-basiclite-linux.x64-21.8.0.0.0dbru.zip -o /tmp/instantclient-basiclite-linux.x64-21.8.0.0.0dbru.zip
          unzip -q /tmp/instantclient-basiclite-linux.x64-21.8.0.0.0dbru.zip -d /opt/oracle/
          sudo sh -c "echo /opt/oracle/instantclient_21_8 > /etc/ld.so.conf.d/oracle-instantclient.conf"
          sudo ldconfig
          cd core
          pip install wheel
          CASS_DRIVER_NO_CYTHON=1 pip install cassandra-driver
          pip install .
          pip install .[test]

      - name: Set TC_MAX_TRIES environment variable
        run: echo "export TC_MAX_TRIES=1200" >> $GITHUB_ENV

      - name: Run tests
        run: |
          cd integration-tests
          PYTHONPATH=. python -m pytest -n auto -s --log-cli-level=DEBUG -k db2
