name: unit-tests
on:
  workflow_dispatch:
  pull_request:

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      # Setup Python (faster than using Python container)
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          cd core
          pip install wheel
          CASS_DRIVER_NO_CYTHON=1 pip install cassandra-driver
          pip install poetry
          poetry install
          poetry install --extras "test"

      - name: Run tests
        run: |
          cd core
          PYTHONPATH=src python -m pytest -s --log-cli-level=DEBUG
